//API 2 
GET http://localhost:3000/todos/:todoId/

// API 3 
GET http://localhost:3000/agenda/

###
//API 4
POST http://localhost:3000/todos/
Content-Type:appliaction/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

